=== elzup/unicode-palette/data/unicode-blocks.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "UnicodeBlocksData",
  "type": "object",
  "required": [
    "version",
    "generatedAt",
    "totalBlocks",
    "bmpBlocks",
    "blocks"
  ],
  "properties": {
    "version": {
      "type": "string"
    },
    "generatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "totalBlocks": {
      "type": "integer",
      "minimum": 0
    },
    "bmpBlocks": {
      "type": "integer",
      "minimum": 0
    },
    "blocks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "displayName",
          "blockStart",
          "blockEnd",
          "definedCount",
          "unassignedCount",
          "ranges"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "blockStart": {
            "type": "integer",
            "minimum": 0
          },
          "blockEnd": {
            "type": "integer",
            "minimum": 0
          },
          "definedCount": {
            "type": "integer",
            "minimum": 0
          },
          "unassignedCount": {
            "type": "integer",
            "minimum": 0
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "start",
                "end"
              ],
              "properties": {
                "start": {
                  "type": "integer",
                  "minimum": 0
                },
                "end": {
                  "type": "integer",
                  "minimum": 0
                }
              }
            }
          }
        }
      }
    }
  }
}

=== elzup/unicode-palette/data/unicode-blocks.min.json
{"version":"17.0.0","generatedAt":"2025-12-12T05:00:06.370Z","totalBlocks":346,"bmpBlocks":164,"blocks":[{"name":"Basic_Latin","displayName":"Basic Latin","blockStart":0,"blockEnd":127,"definedCount":128,"unassignedCount":0,"ranges":[{"start":0,"end":127}]},{"name":"Latin_1_Supplement","displayName":"Latin 1 Supplement","blockStart":128,"blockEnd":255,"definedCount":128,"unassignedCount":0,"ranges":[{"start":128,"end":255}]},{"name":"Latin_Extended_A","displayName":"Latin Extended A","blockStart":256,"blockEnd":383,"definedCount":128,"unassignedCount":0,"ranges":[{"start":256,"end":383}]},{"name":"Latin_Extended_B","displayName":"Latin Extended B","blockStart":384,"blockEnd":591,"definedCount":208,"unassignedCount":0,"ranges":[{"start":384,"end":591}]},{"name":"IPA_Extensions","displayName":"IPA Extensions","blockStart":592,"blockEnd":687,"definedCount":96,"unassignedCount":0,"ranges":[{"start":592,"end":687}]},{"name":"Spacing_Modifier_Letters","displayName":"Spacing Modifier Letters","blockStart":688,"blockEnd":767,"definedCount":80,"unassignedCount":0,"ranges":[{"start":688,"end":767}]},{"name":"Combining_Diacritical_Marks","displayName":"Combining Diacritical Marks","blockStart":768,"blockEnd":879,"definedCount":112,"unassignedCount":0,"ranges":[{"start":768,"end":879}]},{"name":"Greek_And_Coptic","displayName":"Greek And Coptic","blockStart":880,"blockEnd":1023,"definedCount":135,"unassignedCount":9,"ranges":[{"start":880,"end":887},{"start":890,"end":895},{"start":900,"end":906},{"start":908,"end":908},{"start":910,"end":929},{"start":931,"end":1023}]},{"name":"Cyrillic","displayName":"Cyrillic","blockStart":1024,"blockEnd":1279,"definedCount":256,"unassignedCount":0,"ranges":[{"start":1024,"end":1279}]},{"name":"Cyrillic_Supplement","displayName":"Cyrillic Supplement","blockStart":1280,"blockEnd":1327,"definedCount":48,"unassignedCount":0,"ranges":[{"start":1280,"end":1327}]},{"name":"Armenian","displayName":"Armenian","blockStart":1328,"blockEnd":1423,"definedCount":91,"unassignedCount":5,"ranges":[{"start":1329,"end":1366},{"start":1369,"end":1418},{"start":1421,"end":1423}]},{"name":"Hebrew","displayName":"Hebrew","blockStart":1424,"blockEnd":1535,"definedCount":88,"unassignedCount":24,"ranges":[{"start":1425,"end":1479},{"start":1488,"end":1514},{"start":1519,"end":1524}]},{"name":"Arabic","displayName":"Arabic","blockStart":1536,"blockEnd":1791,"definedCount":256,"unassignedCount":0,"ranges":[{"start":1536,"end":1791}]},{"name":"Syriac","displayName":"Syriac","blockStart":1792,"blockEnd":1871,"definedCount":77,"unassignedCount":3,"ranges":[{"start":1792,"end":1805},{"start":1807,"end":1866},{"start":1869,"end":1871}]},{"name":"Arabic_Supplement","displayName":"Arabic Supplement","blockStart":1872,"blockEnd":1919,"definedCount":48,"unassignedCount":0,"ranges":[{"start":1872,"end":1919}]},{"name":"Thaana","displayName":"Thaana","blockStart":1920,"blockEnd":1983,"definedCount":50,"unassignedCount":14,"ranges":[{"start":1920,"end":1969}]},{"name":"NKo","displayName":"NKo","blockStart":1984,"blockEnd":2047,"definedCount":62,"unassignedCount":2,"ranges":[{"start":1984,"end":2042},{"start":2045,"end":2047}]},{"name":"Samaritan","displayName":"Samaritan","blockStart":2048,"blockEnd":2111,"definedCount":61,"unassignedCount":3,"ranges":[{"start":2048,"end":2093},{"start":2096,"end":2110}]},{"name":"Mandaic","displayName":"Mandaic","blockStart":2112,"blockEnd":2143,"definedCount":29,"unassignedCount":3,"ranges":[{"start":2112,"end":2139},{"start":2142,"end":2142}]},{"name":"Syriac_Supplement","displayName":"Syriac Supplement","blockStart":2144,"blockEnd":2159,"definedCount":11,"unassignedCount":5,"ranges":[{"start":2144,"end":2154}]},{"name":"Arabic_Extended_B","displayName":"Arabic Extended B","blockStart":2160,"blockEnd":2207,"definedCount":43,"unassignedCount":5,"ranges":[{"start":2160,"end":2193},{"start":2199,"end":2207}]},{"name":"Arabic_Extended_A","displayName":"Arabic Extended A","blockStart":2208,"blockEnd":2303,"definedCount":96,"unassignedCount":0,"ranges":[{"start":2208,"end":2303}]},{"name":"Devanagari","displayName":"Devanagari","blockStart":2304,"blockEnd":2431,"definedCount":128,"unassignedCount":0,"ranges":[{"start":2304,"end":2431}]},{"name":"Bengali","displayName":"Bengali","blockStart":2432,"blockEnd":2559,"definedCount":96,"unassignedCount":32,"ranges":[{"start":2432,"end":2435},{"start":2437,"end":2444},{"start":2447,"end":2448},{"start":2451,"end":2472},{"start":2474,"end":2480},{"start":2482,"end":2482},{"start":2486,"end":2489},{"start":2492,"end":2500},{"start":2503,"end":2504},{"start":2507,"end":2510},{"start":2519,"end":2519},{"start":2524,"end":2525},{"start":2527,"end":2531},{"start":2534,"end":2558}]},{"name":"Gurmukhi","displayName":"Gurmukhi","blockStart":2560,"blockEnd":2687,"definedCount":80,"unassignedCount":48,"ranges":[{"start":2561,"end":2563},{"start":2565,"end":2570},{"start":2575,"end":2576},{"start":2579,"end":2600},{"start":2602,"end":2608},{"start":2610,"end":2611},{"start":2613,"end":2614},{"start":2616,"end":2617},{"start":2620,"end":2620},{"start":2622,"end":2626},{"start":2631,"end":2632},{"start":2635,"end":2637},{"start":2641,"end":2641},{"start":2649,"end":2652},{"start":2654,"end":2654},{"start":2662,"end":2678}]},{"name":"Gujarati","displayName":"Gujarati","blockStart":2688,"blockEnd":2815,"definedCount":91,"unassignedCount":37,"ranges":[{"start":2689,"end":2691},{"start":2693,"end":2701},{"start":2703,"end":2705},{"start":2707,"end":2728},{"start":2730,"end":2736},{"start":2738,"end":2739},{"start":2741,"end":2745},{"start":2748,"end":2757},{"start":2759,"end":2761},{"start":2763,"end":2765},{"start":2768,"end":2768},{"start":2784,"end":2787},{"start":2790,"end":2801},{"start":2809,"end":2815}]},{"name":"Oriya","displayName":"Oriya","blockStart":2816,"blockEnd":2943,"definedCount":91,"unassignedCount":37,"ranges":[{"start":2817,"end":2819},{"start":2821,"end":2828},{"start":2831,"end":2832},{"start":2835,"end":2856},{"start":2858,"end":2864},{"start":2866,"end":2867},{"start":2869,"end":2873},{"start":2876,"end":2884},{"start":2887,"end":2888},{"start":2891,"end":2893},{"start":2901,"end":2903},{"start":2908,"end":2909},{"start":2911,"end":2915},{"start":2918,"end":2935}]},{"name":"Tamil","displayName":"Tamil","blockStart":2944,"blockEnd":3071,"definedCount":72,"unassignedCount":56,"ranges":[{"start":2946,"end":2947},{"start":2949,"end":2954},{"start":2958,"end":2960},{"start":2962,"end":2965},{"start":2969,"end":2970},{"start":2972,"end":2972},{"start":2974,"end":2975},{"start":2979,"end":2980},{"start":2984,"end":2986},{"start":2990,"end":3001},{"start":3006,"end":3010},{"start":3014,"end":3016},{"start":3018,"end":3021},{"start":3024,"end":3024},{"start":3031,"end":3031},{"start":3046,"end":3066}]},{"name":"Telugu","displayName":"Telugu","blockStart":3072,"blockEnd":3199,"definedCount":101,"unassignedCount":27,"ranges":[{"start":3072,"end":3084},{"start":3086,"end":3088},{"start":3090,"end":3112},{"start":3114,"end":3129},{"start":3132,"end":3140},{"start":3142,"end":3144},{"start":3146,"end":3149},{"start":3157,"end":3158},{"start":3160,"end":3162},{"start":3164,"end":3165},{"start":3168,"end":3171},{"start":3174,"end":3183},{"start":3191,"end":3199}]},{"name":"Kannada","displayName":"Kannada","blockStart":3200,"blockEnd":3327,"definedCount":92,"unassignedCount":36,"ranges":[{"start":3200,"end":3212},{"start":3214,"end":3216},{"start":3218,"end":3240},{"start":3242,"end":3251},{"start":3253,"end":3257},{"start":3260,"end":3268},{"start":3270,"end":3272},{"start":3274,"end":3277},{"start":3285,"end":3286},{"start":3292,"end":3294},{"start":3296,"end":3299},{"start":3302,"end":3311},{"start":3313,"end":3315}]},{"name":"Malayalam","displayName":"Malayalam","blockStart":3328,"blockEnd":3455,"definedCount":118,"unassignedCount":10,"ranges":[{"start":3328,"end":3340},{"start":3342,"end":3344},{"start":3346,"end":3396},{"start":3398,"end":3400},{"start":3402,"end":3407},{"start":3412,"end":3427},{"start":3430,"end":3455}]},{"name":"Sinhala","displayName":"Sinhala","blockStart":3456,"blockEnd":3583,"definedCount":91,"unassignedCount":37,"ranges":[{"start":3457,"end":3459},{"start":3461,"end":3478},{"start":3482,"end":3505},{"start":3507,"end":3515},{"start":3517,"end":3517},{"start":3520,"end":3526},{"start":3530,"end":3530},{"start":3535,"end":3540},{"start":3542,"end":3542},{"start":3544,"end":3551},{"start":3558,"end":3567},{"start":3570,"end":3572}]},{"name":"Thai","displayName":"Thai","blockStart":3584,"blockEnd":3711,"definedCount":87,"unassignedCount":41,"ranges":[{"start":3585,"end":3642},{"start":3647,"end":3675}]},{"name":"Lao","displayName":"Lao","blockStart":3712,"blockEnd":3839,"definedCount":83,"unassignedCount":45,"ranges":[{"start":3713,"end":3714},{"start":3716,"end":3716},{"start":3718,"end":3722},{"start":3724,"end":3747},{"start":3749,"end":3749},{"start":3751,"end":3773},{"start":3776,"end":3780},{"start":3782,"end":3782},{"start":3784,"end":3790},{"start":3792,"end":3801},{"start":3804,"end":3807}]},{"name":"Tibetan","displayName":"Tibetan","blockStart":3840,"blockEnd":4095,"definedCount":211,"unassignedCount":45,"ranges":[{"start":3840,"end":3911},{"start":3913,"end":3948},{"start":3953,"end":3991},{"start":3993,"end":4028},{"start":4030,"end":4044},{"start":4046,"end":4058}]},{"name":"Myanmar","displayName":"Myanmar","blockStart":4096,"blockEnd":4255,"definedCount":160,"unassignedCount":0,"ranges":[{"start":4096,"end":4255}]},{"name":"Georgian","displayName":"Georgian","blockStart":4256,"blockEnd":4351,"definedCount":88,"unassignedCount":8,"ranges":[{"start":4256,"end":4293},{"start":4295,"end":4295},{"start":4301,"end":4301},{"start":4304,"end":4351}]},{"name":"Hangul_Jamo","displayName":"Hangul Jamo","blockStart":4352,"blockEnd":4607,"definedCount":256,"unassignedCount":0,"ranges":[{"start":4352,"end":4607}]},{"name":"Ethiopic","displayName":"Ethiopic","blockStart":4608,"blockEnd":4991,"definedCount":358,"unassignedCount":26,"rang
